import type { IconType } from 'react-icons'
import {
  FaReact,
  FaNodeJs,
  FaPython,
  FaAndroid,
  FaJava,
} from 'react-icons/fa'
import {
  SiTypescript,
  SiJavascript,
  SiExpress,
  SiPostgresql,
  SiSqlite,
  SiSocketdotio,
  SiVite,
  SiTailscale,
  SiPm2,
  SiKotlin,
  SiTelegram,
  SiOllama,
  SiTampermonkey,
  SiLeaflet,
  SiReactrouter,
} from 'react-icons/si'
import { FaFilePdf } from 'react-icons/fa6'

export const techIconMap: Record<string, IconType> = {
  React: FaReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  'Node.js': FaNodeJs,
  Express: SiExpress,
  PostgreSQL: SiPostgresql,
  SQLite: SiSqlite,
  'Socket.io': SiSocketdotio,
  Vite: SiVite,
  Tailscale: SiTailscale,
  PM2: SiPm2,
  Android: FaAndroid,
  Kotlin: SiKotlin,
  Java: FaJava,
  Python: FaPython,
  Telegram: SiTelegram,
  Ollama: SiOllama,
  Tampermonkey: SiTampermonkey,
  Leaflet: SiLeaflet,
  'React Router': SiReactrouter,
  jsPDF: FaFilePdf,
}
